"""
Paper 2 v3 -- One-command pipeline (Requirement 13)

Runs scripts 01-07 in order, then the identity/range test suite, then
rebuilds facts.json and output_manifest.csv from scratch (not by
incremental append, to avoid any accumulated inconsistency from
interactive development).

Design notes
------------
- Each stage is run as a SEPARATE subprocess (python3 <script>.py), not
  imported and called in-process. This is deliberate: several stages set
  process environment variables for GDAL/PROJ (see config.QGIS_GDAL_ENV)
  and this keeps that scoped per-subprocess rather than leaking between
  stages or depending on import order.
- Idempotency is handled INSIDE each stage, not here: script 01 already
  skips tiles it has already downloaded; scripts 02-07 are cheap enough
  (33s-73s each) that simply re-running them is simpler and safer than
  adding a second layer of skip-logic here that could drift out of sync
  with what each script actually checks.
- audit_report.md is NOT regenerated by this script. It is a manually
  curated narrative document (investigative write-ups of findings like
  the ANBH quantization spike, the disconnected-components investigation,
  the GM_Error residual bug-and-fix) that is not purely mechanically
  derivable from script output. This is a deliberate scope boundary, not
  an oversight: run_all.py's job is the ANALYTICAL pipeline + machine-
  readable facts.json + file manifest; audit_report.md is the
  human-readable companion, maintained alongside it.
- Per Requirement 14, no manuscript text exists yet and this script does
  not produce any -- it stops at facts.json/output_manifest.csv.

Usage
-----
    python scripts/revision_v3/run_all.py                  # full pipeline
    python scripts/revision_v3/run_all.py --from 4          # resume from script 04
    python scripts/revision_v3/run_all.py --only 6          # re-run just script 06
    python scripts/revision_v3/run_all.py --skip-tests      # skip pytest stage
"""
from __future__ import annotations
import argparse
import hashlib
import json
import logging
import subprocess
import sys
import time
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
import config as cfg

logging.basicConfig(level=cfg.LOG_LEVEL, format="%(asctime)s  %(levelname)-8s  %(message)s",
                     datefmt="%Y-%m-%d %H:%M:%S")
log = logging.getLogger(__name__)

REV3 = cfg.REVISION_V3
PY = sys.executable

STAGES = [
    (1, "01_acquire_ghsl_height.py", "Acquire GHSL AGBH/ANBH 2018 from JRC, checksum, provenance"),
    (2, "02_process_agbh_anbh_grid.py", "Aggregate to 500 m grid by area (zonal stats against real grid polygons)"),
    (3, "03_sample_definitions_and_sensitivity.py", "National-footprint vs valid-height samples, threshold sensitivity"),
    (4, "04_models_primary.py", "Nested OLS + spatial error models, ANBH primary / AGBH robustness"),
    (5, "05_weights_diagnostics.py", "Queen / Queen+KNN1-islands / KNN-8 weights audit and sensitivity"),
    (6, "06_typology_v3.py", "Typology rebuild: ANBH x pre-2018 growth, full sensitivity tables"),
    (7, "07_validation_module.py", "Spatial plausibility, cross-dataset consistency, manual validation sample"),
]

# Every output this pipeline is known to produce, for the final manifest.
# Rebuilt from scratch each run (not appended) so the manifest never drifts
# out of sync with what actually exists on disk.
KNOWN_OUTPUTS = [
    ("01_raw_data/ghsl/agbh_2018_v3.tif", "script 01", "AGBH raster, clipped to Ghana bbox"),
    ("01_raw_data/ghsl/anbh_2018_v3.tif", "script 01", "ANBH raster, clipped to Ghana bbox"),
    ("01_raw_data/ghsl/provenance_agbh_anbh_2018.json", "script 01", "Full provenance: URLs, DOI, checksums, CRS, nodata"),
    ("02_processed_data/ghsl_layers_v3/agbh_anbh_grid_500m.parquet", "script 02", "National 500m grid: AGBH mean, built_fraction mean, ANBH derived"),
    ("02_processed_data/ghsl_layers_v3/sample_definitions.parquet", "script 03", "Per-cell sample flags: national-footprint + 5 valid-height thresholds"),
    ("04_outputs/paper2_v3/tables/T_sample_sensitivity.csv", "script 03", "Threshold sensitivity summary table"),
    ("04_outputs/paper2_v3/tables/T_models_ols.csv", "script 04", "OLS coefficients, SEs, CIs, standardized coefs"),
    ("04_outputs/paper2_v3/tables/T_models_spatial.csv", "script 04", "Spatial error coefficients, SEs, CIs, lambda"),
    ("04_outputs/paper2_v3/tables/T_models_fit_and_moran.csv", "script 04", "R2/pseudo-R2, AIC, 3-way Moran's I"),
    ("04_outputs/paper2_v3/tables/T_models_vif.csv", "script 04", "VIF per predictor"),
    ("04_outputs/paper2_v3/tables/sample_construction_report.json", "script 04", "Exact sample dropout counts and reasons"),
    ("04_outputs/paper2_v3/tables/T_weights_audit.csv", "script 05", "Islands/components/neighbor-count audit"),
    ("04_outputs/paper2_v3/tables/T_weights_sensitivity.csv", "script 05", "Model C under 3 weights specs"),
    ("02_processed_data/ghsl_layers_v3/typology_v3.parquet", "script 06", "Per-cell typology class (ANBH x pre-2018 growth)"),
    ("04_outputs/paper2_v3/tables/T_typology_median.csv", "script 06", "Median-split class counts and shares"),
    ("04_outputs/paper2_v3/tables/T_typology_profile.csv", "script 06", "Class profile: mean/median ANBH and growth"),
    ("04_outputs/paper2_v3/tables/T_typology_tertile_full.csv", "script 06", "Full 3x3 tertile crosstab"),
    ("04_outputs/paper2_v3/tables/T_typology_quartile_full.csv", "script 06", "Full 4x4 quartile crosstab"),
    ("04_outputs/paper2_v3/tables/T_typology_sensitivity_summary.csv", "script 06", "Diagonal/off-diagonal share by scheme"),
    ("04_outputs/paper2_v3/tables/T_typology_agbh_matched_comparison.csv", "script 06", "ANBH vs AGBH diagonal concordance, sample/axis/tie-rule held constant"),
    ("04_outputs/paper2_v3/tables/T_typology_predictor_profile.csv", "script 06", "Section 4.7 regression predictors by typology class (manuscript Table 6)"),
    ("04_outputs/paper2_v3/tables/typology_construction_report.json", "script 06", "Exact medians, tie counts, tie rule"),
    ("04_outputs/paper2_v3/tables/T_validation_A_spatial_plausibility.csv", "script 07", "Typology class share by independent region tier"),
    ("04_outputs/paper2_v3/tables/T_validation_B_cross_dataset.csv", "script 07", "ANBH/AGBH vs independent V3 building-size metrics"),
    ("02_processed_data/validation_samples/v3_manual_validation_sample.parquet", "script 07", "Stratified 120-cell manual validation sample"),
    ("04_outputs/paper2_v3/tables/v3_manual_validation_coding_template.csv", "script 07", "Blank coding template, GHSL values pre-filled"),
    ("scripts/revision_v3/facts.json", "build_facts_json.py", "Consolidated machine-readable findings"),
    ("scripts/revision_v3/audit_report.md", "manual", "Human-readable audit narrative (not auto-generated)"),
    ("04_outputs/paper2_v3/figures/fig01_anbh_map.png", "08_manuscript_figures.py", "ANBH map (manuscript Fig. 1)"),
    ("04_outputs/paper2_v3/figures/fig02_agbh_map.png", "08_manuscript_figures.py", "AGBH map (manuscript Fig. 2)"),
    ("04_outputs/paper2_v3/figures/fig03_typology_map.png", "08_manuscript_figures.py", "Typology map (manuscript Fig. 4)"),
    ("04_outputs/paper2_v3/figures/fig04_regression_coefficients.png", "08_manuscript_figures.py", "Model C coefficient plot (manuscript Fig. 3)"),
    ("04_outputs/paper2_v3/figures/figA2_sample_flow.png", "08_manuscript_figures.py", "Sample-flow diagram (manuscript Fig. A2)"),
    ("04_outputs/manuscript/paper2_v3_draft.md", "manual", "v3 manuscript (not auto-generated)"),
]


def sha256_16(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()[:16]


def run_stage(num: int, script: str, desc: str) -> tuple[bool, float]:
    log.info("=== Stage %d: %s -- %s ===", num, script, desc)
    t0 = time.time()
    log_path = REV3 / f"_run_all_stage{num:02d}.log"
    with open(log_path, "w") as lf:
        r = subprocess.run([PY, str(REV3 / script)], stdout=lf, stderr=subprocess.STDOUT)
    elapsed = time.time() - t0
    ok = r.returncode == 0
    status = "OK" if ok else f"FAILED (exit {r.returncode})"
    log.info("  Stage %d %s in %.1fs (log: %s)", num, status, elapsed, log_path.name)
    if not ok:
        tail = log_path.read_text().splitlines()[-25:]
        log.error("  Last 25 lines of stage %d log:\n%s", num, "\n".join(tail))
    return ok, elapsed


def run_tests() -> bool:
    log.info("=== Test suite: tests/test_identity_range.py ===")
    r = subprocess.run([PY, "-m", "pytest", str(REV3 / "tests" / "test_identity_range.py"), "-v"],
                        capture_output=True, text=True)
    print(r.stdout[-3000:])
    ok = r.returncode == 0
    log.info("  Test suite %s", "PASSED" if ok else "FAILED")
    return ok


def rebuild_manifest() -> None:
    log.info("=== Rebuilding output_manifest.csv from scratch ===")
    rows = []
    for relpath, producer, desc in KNOWN_OUTPUTS:
        p = cfg.PROJECT_ROOT / relpath
        if not p.exists():
            rows.append({"path": relpath, "producer_script": producer, "description": desc,
                         "size_bytes": None, "shape": "MISSING", "sha256_16": None})
            continue
        shape = "n/a"
        if p.suffix == ".parquet":
            try:
                shape = f"{pd.read_parquet(p).shape[0]} rows x {pd.read_parquet(p).shape[1]} cols"
            except Exception:
                shape = "n/a (unreadable)"
        elif p.suffix == ".csv":
            try:
                df = pd.read_csv(p)
                shape = f"{df.shape[0]} rows x {df.shape[1]} cols"
            except Exception:
                shape = "n/a (unreadable)"
        size = p.stat().st_size
        checksum = sha256_16(p) if size < 500_000_000 else "skipped (large file, see provenance json)"
        rows.append({"path": relpath, "producer_script": producer, "description": desc,
                     "size_bytes": size, "shape": shape, "sha256_16": checksum})
    manifest = pd.DataFrame(rows)
    manifest.to_csv(REV3 / "output_manifest.csv", index=False)
    n_missing = int((manifest["shape"] == "MISSING").sum())
    log.info("  Manifest: %d files tracked, %d missing", len(manifest), n_missing)
    if n_missing:
        log.warning("  Missing files:\n%s", manifest[manifest.shape == "MISSING"][["path"]].to_string(index=False))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--from", dest="from_stage", type=int, default=1, help="Resume from this stage number")
    ap.add_argument("--only", type=int, default=None, help="Run only this stage number")
    ap.add_argument("--skip-tests", action="store_true", help="Skip the pytest stage")
    ap.add_argument("--skip-facts", action="store_true", help="Skip rebuilding facts.json")
    args = ap.parse_args()

    t0 = time.time()
    stages_to_run = [s for s in STAGES if s[0] == args.only] if args.only else \
                     [s for s in STAGES if s[0] >= args.from_stage]

    results = []
    for num, script, desc in stages_to_run:
        ok, elapsed = run_stage(num, script, desc)
        results.append({"stage": num, "script": script, "ok": ok, "elapsed_s": round(elapsed, 1)})
        if not ok:
            log.error("Pipeline stopped at stage %d (%s). Fix and re-run with --from %d.", num, script, num)
            print(json.dumps(results, indent=2))
            sys.exit(1)

    tests_ok = True
    if not args.skip_tests:
        tests_ok = run_tests()

    if not args.skip_facts:
        log.info("=== Rebuilding facts.json ===")
        r = subprocess.run([PY, str(REV3 / "build_facts_json.py")], capture_output=True, text=True)
        if r.returncode != 0:
            log.error("build_facts_json.py failed:\n%s", r.stderr[-2000:])
        else:
            log.info("  facts.json rebuilt.")

    rebuild_manifest()

    total = time.time() - t0
    log.info("=== Pipeline complete in %.1fs ===", total)
    log.info("Stages run: %s", [(r["stage"], "OK" if r["ok"] else "FAIL") for r in results])
    log.info("Test suite: %s", "PASSED" if tests_ok else "FAILED (see above)")
    log.info("See scripts/revision_v3/audit_report.md for the human-readable narrative "
              "(not regenerated by this script -- manually maintained).")
    if not tests_ok:
        sys.exit(1)


if __name__ == "__main__":
    main()
